import {
  LayoutDashboard,
  Users,
  UserPlus,
  Briefcase,
  Folder,
  CheckSquare,
  Share2,
  MessageCircle,
  Star,
  FileText,
  BarChart3,
  Bot,
  Settings,
  Phone,
  Bell,
  Landmark,
  Globe,
  Zap,
  ArrowRightLeft,
  History,
  Calendar,
  Shield,
  Lock,
} from 'lucide-react';

export interface ModuleDefinition {
  id: string;
  label: string;
  path: string;
  icon: React.ElementType;
  description: string;
  isCore: boolean;
  permissions: string[];
}

export const MODULES: ModuleDefinition[] = [
  {
    id: 'authentication',
    label: 'Authentication',
    path: '/auth/login',
    icon: Lock,
    description: 'User login, registration, password reset, and session management. Core security layer.',
    isCore: true,
    permissions: [],
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: LayoutDashboard,
    description: 'Main dashboard with overview stats, charts, and recent activity widgets.',
    isCore: true,
    permissions: ['dashboard'],
  },
  {
    id: 'settings',
    label: 'Company Settings',
    path: '/dashboard/settings',
    icon: Settings,
    description: 'Company profile, branding, notification preferences, and security configuration.',
    isCore: true,
    permissions: ['settings'],
  },
  {
    id: 'rbac',
    label: 'RBAC',
    path: '/dashboard/team',
    icon: Shield,
    description: 'Role-Based Access Control. Manages user roles, permissions, and access levels.',
    isCore: true,
    permissions: ['team'],
  },
  {
    id: 'crm',
    label: 'CRM',
    path: '/dashboard/crm',
    icon: UserPlus,
    description: 'Customer Relationship Management pipeline with lead tracking and conversion.',
    isCore: false,
    permissions: ['crm', 'leads'],
  },
  {
    id: 'leads',
    label: 'Leads',
    path: '/dashboard/leads',
    icon: Users,
    description: 'Lead management with follow-ups, status tracking, and assignment.',
    isCore: false,
    permissions: ['leads', 'crm'],
  },
  {
    id: 'clients',
    label: 'Clients',
    path: '/dashboard/clients',
    icon: Briefcase,
    description: 'Client management with service tracking, documents, and communication history.',
    isCore: false,
    permissions: ['clients'],
  },
  {
    id: 'portal-clients',
    label: 'Portal Clients',
    path: '/dashboard/portal-clients',
    icon: Globe,
    description: 'Admin management of client portal accounts and access.',
    isCore: false,
    permissions: ['portal'],
  },
  {
    id: 'projects',
    label: 'Projects',
    path: '/dashboard/projects',
    icon: Folder,
    description: 'Project management with task tracking, milestones, and team collaboration.',
    isCore: false,
    permissions: ['projects'],
  },
  {
    id: 'tasks',
    label: 'Tasks',
    path: '/dashboard/tasks',
    icon: CheckSquare,
    description: 'Task management with priority, status, due dates, and assignment.',
    isCore: false,
    permissions: ['tasks'],
  },
  {
    id: 'calendar',
    label: 'Calendar',
    path: '/dashboard/calendar',
    icon: Calendar,
    description: 'Calendar with day/week/month/agenda views, meetings, and lead follow-ups.',
    isCore: false,
    permissions: ['dashboard'],
  },
  {
    id: 'social',
    label: 'Social Media',
    path: '/dashboard/social',
    icon: Share2,
    description: 'Social media management and scheduling across multiple platforms.',
    isCore: false,
    permissions: ['social'],
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    path: '/dashboard/whatsapp',
    icon: MessageCircle,
    description: 'WhatsApp bulk messaging, templates, and conversation management.',
    isCore: false,
    permissions: ['whatsapp'],
  },
  {
    id: 'reviews',
    label: 'Reviews',
    path: '/dashboard/reviews',
    icon: Star,
    description: 'Google Reviews management with reply tracking and analytics.',
    isCore: false,
    permissions: ['reviews'],
  },
  {
    id: 'invoices',
    label: 'Invoices',
    path: '/dashboard/invoices',
    icon: FileText,
    description: 'Invoice creation, tracking, and payment management.',
    isCore: false,
    permissions: ['invoices'],
  },
  {
    id: 'gst',
    label: 'GST',
    path: '/dashboard/gst',
    icon: Landmark,
    description: 'GST returns filing, client management, documents, and reports.',
    isCore: false,
    permissions: ['gst'],
  },
  {
    id: 'telecaller',
    label: 'Telecaller',
    path: '/dashboard/telecaller',
    icon: Phone,
    description: 'Telecaller module with call tracking, lead assignment, and performance reports.',
    isCore: false,
    permissions: ['telecaller'],
  },
  {
    id: 'lead-integrations',
    label: 'Lead Integrations',
    path: '/dashboard/lead-integrations',
    icon: Zap,
    description: 'External lead source integrations with auto-sync and webhook management.',
    isCore: false,
    permissions: ['lead_integrations'],
  },
  {
    id: 'auto-assignment',
    label: 'Auto Assignment',
    path: '/dashboard/auto-assignment',
    icon: ArrowRightLeft,
    description: 'Automatic lead assignment rules based on round-robin and skill-based routing.',
    isCore: false,
    permissions: ['settings'],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    path: '/dashboard/notifications',
    icon: Bell,
    description: 'Notification center with reminders, alerts, and task completion updates.',
    isCore: false,
    permissions: ['notifications'],
  },
  {
    id: 'activity-logs',
    label: 'Activity Logs',
    path: '/dashboard/activity-logs',
    icon: History,
    description: 'Audit trail of all user activities with filtering and CSV export.',
    isCore: false,
    permissions: ['dashboard'],
  },
  {
    id: 'reports',
    label: 'Reports',
    path: '/dashboard/reports',
    icon: BarChart3,
    description: 'Business intelligence reports with charts and analytics dashboards.',
    isCore: false,
    permissions: ['reports'],
  },
  {
    id: 'ai',
    label: 'AI Assistant',
    path: '/dashboard/ai',
    icon: Bot,
    description: 'AI-powered assistant for content generation, analysis, and automation.',
    isCore: false,
    permissions: ['ai', 'dashboard'],
  },
];

export const CORE_MODULE_IDS = MODULES.filter((m) => m.isCore).map((m) => m.id);

export const DEFAULT_ENABLED_MODULES = MODULES.map((m) => m.id);
